ТЗ 9
LenzFF/lenzfilmorate pull request #1
Opened 2023-02-09 20:57 UTC by LenzFF

123

2023-02-09 21:03 UTC, LenzFF commented
Вроде все работает

2023-02-10 00:22 UTC, db-exp requested changes

2023-02-10 00:22 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/Controller.java
> +    public void validate(T item) {
чтобы не писать пустой метод можно его сделать abstract

2023-02-10 00:22 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film update(@Valid @RequestBody Film film) {
не хватает override

2023-02-10 00:22 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@RequestBody Film film) {
не хватает override

2023-02-10 00:22 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void validate(Film film) {
не хватает override

2023-02-10 00:22 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User create(@Valid @RequestBody User user) {
не хватает override

2023-02-10 00:22 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User update(@Valid @RequestBody User user) {
не хватает override

2023-02-10 00:22 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void validate(User user) {
не хватает override

2023-02-10 00:22 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@RequestBody Film film) {
не хватает Valid

2023-02-10 08:20 UTC, LenzFF commented
Спасибо за правки!

2023-02-10 12:40 UTC, db-exp approved these changes

2023-02-17 09:26 UTC, merged