Привет! Проверь пожалуйста!
LenzFF/lenzfilmorate pull request #2
Opened 2023-02-23 21:50 UTC by LenzFF

2023-02-24 19:32 UTC, db-exp requested changes

2023-02-24 19:32 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorsHandler.java
> +    @ExceptionHandler({IllegalArgumentException.class, NullPointerException.class})
NullPointer не нужно и нехорошо ловить)

2023-02-24 21:02 UTC, LenzFF commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorsHandler.java
> +    @ExceptionHandler({IllegalArgumentException.class, NullPointerException.class})
Поправил, спасибо!

2023-02-25 08:41 UTC, db-exp approved these changes

2023-02-25 09:15 UTC, merged